apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: volkslieder
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: volkslieder:latest
