apiVersion: v1
kind: Service
metadata:
  name: volkslieder-runoregi
spec:
  selector:
    app: volkslieder
  ports:
    - port: 8000
      targetPort: 8000
      name: runoregi
---
apiVersion: v1
kind: Service
metadata:
  name: volkslieder-shiny
spec:
  selector:
    app: volkslieder
  ports:
    - port: 3838
      targetPort: 3838
      name: shiny
